/*
 * This file is generated by jOOQ.
 */
package org.jooq.sample.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;
import org.jooq.sample.tables.AllPersons;
import org.jooq.sample.udt.records.UdtAddressRecord;
import org.jooq.sample.udt.records.UdtPersonRecord;
import org.jooq.sample.udt.records.UdtPhoneRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllPersonsRecord extends TableRecordImpl<AllPersonsRecord> implements Record3<UdtPersonRecord, UdtAddressRecord[], UdtPhoneRecord[]> {

    private static final long serialVersionUID = -557875458;

    /**
     * Setter for <code>jooq_sample.all_persons.person</code>.
     */
    public void setPerson(UdtPersonRecord value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq_sample.all_persons.person</code>.
     */
    public UdtPersonRecord getPerson() {
        return (UdtPersonRecord) get(0);
    }

    /**
     * Setter for <code>jooq_sample.all_persons.addresses</code>.
     */
    public void setAddresses(UdtAddressRecord... value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq_sample.all_persons.addresses</code>.
     */
    public UdtAddressRecord[] getAddresses() {
        return (UdtAddressRecord[]) get(1);
    }

    /**
     * Setter for <code>jooq_sample.all_persons.phones</code>.
     */
    public void setPhones(UdtPhoneRecord... value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooq_sample.all_persons.phones</code>.
     */
    public UdtPhoneRecord[] getPhones() {
        return (UdtPhoneRecord[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UdtPersonRecord, UdtAddressRecord[], UdtPhoneRecord[]> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UdtPersonRecord, UdtAddressRecord[], UdtPhoneRecord[]> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UdtPersonRecord> field1() {
        return AllPersons.ALL_PERSONS.PERSON;
    }

    @Override
    public Field<UdtAddressRecord[]> field2() {
        return AllPersons.ALL_PERSONS.ADDRESSES;
    }

    @Override
    public Field<UdtPhoneRecord[]> field3() {
        return AllPersons.ALL_PERSONS.PHONES;
    }

    @Override
    public UdtPersonRecord component1() {
        return getPerson();
    }

    @Override
    public UdtAddressRecord[] component2() {
        return getAddresses();
    }

    @Override
    public UdtPhoneRecord[] component3() {
        return getPhones();
    }

    @Override
    public UdtPersonRecord value1() {
        return getPerson();
    }

    @Override
    public UdtAddressRecord[] value2() {
        return getAddresses();
    }

    @Override
    public UdtPhoneRecord[] value3() {
        return getPhones();
    }

    @Override
    public AllPersonsRecord value1(UdtPersonRecord value) {
        setPerson(value);
        return this;
    }

    @Override
    public AllPersonsRecord value2(UdtAddressRecord... value) {
        setAddresses(value);
        return this;
    }

    @Override
    public AllPersonsRecord value3(UdtPhoneRecord... value) {
        setPhones(value);
        return this;
    }

    @Override
    public AllPersonsRecord values(UdtPersonRecord value1, UdtAddressRecord[] value2, UdtPhoneRecord[] value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AllPersonsRecord
     */
    public AllPersonsRecord() {
        super(AllPersons.ALL_PERSONS);
    }

    /**
     * Create a detached, initialised AllPersonsRecord
     */
    public AllPersonsRecord(UdtPersonRecord person, UdtAddressRecord[] addresses, UdtPhoneRecord[] phones) {
        super(AllPersons.ALL_PERSONS);

        set(0, person);
        set(1, addresses);
        set(2, phones);
    }
}
