/*
 * This file is generated by jOOQ.
 */
package org.jooq.sample.udt.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UDTRecordImpl;
import org.jooq.sample.udt.FullPersonRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FullPersonRecordRecord extends UDTRecordImpl<FullPersonRecordRecord> implements Record3<UdtPersonRecord, UdtAddressRecord[], UdtPhoneRecord[]> {

    private static final long serialVersionUID = 1877555351;

    /**
     * Setter for <code>jooq_sample.full_person_record.person</code>.
     */
    public void setPerson(UdtPersonRecord value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq_sample.full_person_record.person</code>.
     */
    public UdtPersonRecord getPerson() {
        return (UdtPersonRecord) get(0);
    }

    /**
     * Setter for <code>jooq_sample.full_person_record.addresses</code>.
     */
    public void setAddresses(UdtAddressRecord... value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq_sample.full_person_record.addresses</code>.
     */
    public UdtAddressRecord[] getAddresses() {
        return (UdtAddressRecord[]) get(1);
    }

    /**
     * Setter for <code>jooq_sample.full_person_record.phones</code>.
     */
    public void setPhones(UdtPhoneRecord... value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooq_sample.full_person_record.phones</code>.
     */
    public UdtPhoneRecord[] getPhones() {
        return (UdtPhoneRecord[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UdtPersonRecord, UdtAddressRecord[], UdtPhoneRecord[]> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UdtPersonRecord, UdtAddressRecord[], UdtPhoneRecord[]> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UdtPersonRecord> field1() {
        return FullPersonRecord.PERSON;
    }

    @Override
    public Field<UdtAddressRecord[]> field2() {
        return FullPersonRecord.ADDRESSES;
    }

    @Override
    public Field<UdtPhoneRecord[]> field3() {
        return FullPersonRecord.PHONES;
    }

    @Override
    public UdtPersonRecord component1() {
        return getPerson();
    }

    @Override
    public UdtAddressRecord[] component2() {
        return getAddresses();
    }

    @Override
    public UdtPhoneRecord[] component3() {
        return getPhones();
    }

    @Override
    public UdtPersonRecord value1() {
        return getPerson();
    }

    @Override
    public UdtAddressRecord[] value2() {
        return getAddresses();
    }

    @Override
    public UdtPhoneRecord[] value3() {
        return getPhones();
    }

    @Override
    public FullPersonRecordRecord value1(UdtPersonRecord value) {
        setPerson(value);
        return this;
    }

    @Override
    public FullPersonRecordRecord value2(UdtAddressRecord... value) {
        setAddresses(value);
        return this;
    }

    @Override
    public FullPersonRecordRecord value3(UdtPhoneRecord... value) {
        setPhones(value);
        return this;
    }

    @Override
    public FullPersonRecordRecord values(UdtPersonRecord value1, UdtAddressRecord[] value2, UdtPhoneRecord[] value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FullPersonRecordRecord
     */
    public FullPersonRecordRecord() {
        super(FullPersonRecord.FULL_PERSON_RECORD);
    }

    /**
     * Create a detached, initialised FullPersonRecordRecord
     */
    public FullPersonRecordRecord(UdtPersonRecord person, UdtAddressRecord[] addresses, UdtPhoneRecord[] phones) {
        super(FullPersonRecord.FULL_PERSON_RECORD);

        set(0, person);
        set(1, addresses);
        set(2, phones);
    }
}
