/*
 * This file is generated by jOOQ.
 */
package org.jooq.sample.udt.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UDTRecordImpl;
import org.jooq.sample.udt.UdtAddress;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UdtAddressRecord extends UDTRecordImpl<UdtAddressRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = -204371441;

    /**
     * Setter for <code>jooq_sample.udt_address.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq_sample.udt_address.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>jooq_sample.udt_address.address_1</code>.
     */
    public void setAddress_1(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq_sample.udt_address.address_1</code>.
     */
    public String getAddress_1() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jooq_sample.udt_address.city</code>.
     */
    public void setCity(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooq_sample.udt_address.city</code>.
     */
    public String getCity() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UdtAddress.ID;
    }

    @Override
    public Field<String> field2() {
        return UdtAddress.ADDRESS_1;
    }

    @Override
    public Field<String> field3() {
        return UdtAddress.CITY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAddress_1();
    }

    @Override
    public String component3() {
        return getCity();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAddress_1();
    }

    @Override
    public String value3() {
        return getCity();
    }

    @Override
    public UdtAddressRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UdtAddressRecord value2(String value) {
        setAddress_1(value);
        return this;
    }

    @Override
    public UdtAddressRecord value3(String value) {
        setCity(value);
        return this;
    }

    @Override
    public UdtAddressRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UdtAddressRecord
     */
    public UdtAddressRecord() {
        super(UdtAddress.UDT_ADDRESS);
    }

    /**
     * Create a detached, initialised UdtAddressRecord
     */
    public UdtAddressRecord(Long id, String address_1, String city) {
        super(UdtAddress.UDT_ADDRESS);

        set(0, id);
        set(1, address_1);
        set(2, city);
    }
}
