/*
 * This file is generated by jOOQ.
 */
package org.jooq.sample.udt.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UDTRecordImpl;
import org.jooq.sample.udt.UdtPerson;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UdtPersonRecord extends UDTRecordImpl<UdtPersonRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = -153453692;

    /**
     * Setter for <code>jooq_sample.udt_person.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq_sample.udt_person.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>jooq_sample.udt_person.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq_sample.udt_person.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UdtPerson.ID;
    }

    @Override
    public Field<String> field2() {
        return UdtPerson.NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public UdtPersonRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UdtPersonRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UdtPersonRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UdtPersonRecord
     */
    public UdtPersonRecord() {
        super(UdtPerson.UDT_PERSON);
    }

    /**
     * Create a detached, initialised UdtPersonRecord
     */
    public UdtPersonRecord(Long id, String name) {
        super(UdtPerson.UDT_PERSON);

        set(0, id);
        set(1, name);
    }
}
