/*
 * This file is generated by jOOQ.
 */
package org.jooq.sample.udt.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UDTRecordImpl;
import org.jooq.sample.udt.UdtPhone;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UdtPhoneRecord extends UDTRecordImpl<UdtPhoneRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 459795354;

    /**
     * Setter for <code>jooq_sample.udt_phone.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq_sample.udt_phone.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>jooq_sample.udt_phone.digits</code>.
     */
    public void setDigits(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq_sample.udt_phone.digits</code>.
     */
    public String getDigits() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UdtPhone.ID;
    }

    @Override
    public Field<String> field2() {
        return UdtPhone.DIGITS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDigits();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDigits();
    }

    @Override
    public UdtPhoneRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UdtPhoneRecord value2(String value) {
        setDigits(value);
        return this;
    }

    @Override
    public UdtPhoneRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UdtPhoneRecord
     */
    public UdtPhoneRecord() {
        super(UdtPhone.UDT_PHONE);
    }

    /**
     * Create a detached, initialised UdtPhoneRecord
     */
    public UdtPhoneRecord(Long id, String digits) {
        super(UdtPhone.UDT_PHONE);

        set(0, id);
        set(1, digits);
    }
}
