/*
 * This file is generated by jOOQ.
 */
package org.jooq.sample.udt;


import javax.annotation.Generated;

import org.jooq.Schema;
import org.jooq.UDTField;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;
import org.jooq.impl.UDTImpl;
import org.jooq.sample.JooqSample;
import org.jooq.sample.udt.records.FullPersonRecordRecord;
import org.jooq.sample.udt.records.UdtAddressRecord;
import org.jooq.sample.udt.records.UdtPersonRecord;
import org.jooq.sample.udt.records.UdtPhoneRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FullPersonRecord extends UDTImpl<FullPersonRecordRecord> {

    private static final long serialVersionUID = 1479999528;

    /**
     * The reference instance of <code>jooq_sample.full_person_record</code>
     */
    public static final FullPersonRecord FULL_PERSON_RECORD = new FullPersonRecord();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FullPersonRecordRecord> getRecordType() {
        return FullPersonRecordRecord.class;
    }

    /**
     * The attribute <code>jooq_sample.full_person_record.person</code>.
     */
    public static final UDTField<FullPersonRecordRecord, UdtPersonRecord> PERSON = createField(DSL.name("person"), org.jooq.sample.udt.UdtPerson.UDT_PERSON.getDataType(), FULL_PERSON_RECORD, "");

    /**
     * The attribute <code>jooq_sample.full_person_record.addresses</code>.
     */
    public static final UDTField<FullPersonRecordRecord, UdtAddressRecord[]> ADDRESSES = createField(DSL.name("addresses"), org.jooq.sample.udt.UdtAddress.UDT_ADDRESS.getDataType().getArrayDataType(), FULL_PERSON_RECORD, "");

    /**
     * The attribute <code>jooq_sample.full_person_record.phones</code>.
     */
    public static final UDTField<FullPersonRecordRecord, UdtPhoneRecord[]> PHONES = createField(DSL.name("phones"), org.jooq.sample.udt.UdtPhone.UDT_PHONE.getDataType().getArrayDataType(), FULL_PERSON_RECORD, "");

    /**
     * No further instances allowed
     */
    private FullPersonRecord() {
        super("full_person_record", null, null, false);
    }

    @Override
    public Schema getSchema() {
        return JooqSample.JOOQ_SAMPLE != null ? JooqSample.JOOQ_SAMPLE : new SchemaImpl(DSL.name("jooq_sample"));
    }
}
