/*
 * This file is generated by jOOQ.
 */
package org.jooq.sample.udt;


import javax.annotation.Generated;

import org.jooq.Schema;
import org.jooq.UDTField;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;
import org.jooq.impl.UDTImpl;
import org.jooq.sample.JooqSample;
import org.jooq.sample.udt.records.UdtAddressRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UdtAddress extends UDTImpl<UdtAddressRecord> {

    private static final long serialVersionUID = 750001537;

    /**
     * The reference instance of <code>jooq_sample.udt_address</code>
     */
    public static final UdtAddress UDT_ADDRESS = new UdtAddress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UdtAddressRecord> getRecordType() {
        return UdtAddressRecord.class;
    }

    /**
     * The attribute <code>jooq_sample.udt_address.id</code>.
     */
    public static final UDTField<UdtAddressRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT, UDT_ADDRESS, "");

    /**
     * The attribute <code>jooq_sample.udt_address.address_1</code>.
     */
    public static final UDTField<UdtAddressRecord, String> ADDRESS_1 = createField(DSL.name("address_1"), org.jooq.impl.SQLDataType.CLOB, UDT_ADDRESS, "");

    /**
     * The attribute <code>jooq_sample.udt_address.city</code>.
     */
    public static final UDTField<UdtAddressRecord, String> CITY = createField(DSL.name("city"), org.jooq.impl.SQLDataType.CLOB, UDT_ADDRESS, "");

    /**
     * No further instances allowed
     */
    private UdtAddress() {
        super("udt_address", null, null, false);
    }

    @Override
    public Schema getSchema() {
        return JooqSample.JOOQ_SAMPLE != null ? JooqSample.JOOQ_SAMPLE : new SchemaImpl(DSL.name("jooq_sample"));
    }
}
