/*
 * This file is generated by jOOQ.
 */
package org.jooq.sample.udt;


import javax.annotation.Generated;

import org.jooq.Schema;
import org.jooq.UDTField;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;
import org.jooq.impl.UDTImpl;
import org.jooq.sample.JooqSample;
import org.jooq.sample.udt.records.UdtPersonRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UdtPerson extends UDTImpl<UdtPersonRecord> {

    private static final long serialVersionUID = 617378804;

    /**
     * The reference instance of <code>jooq_sample.udt_person</code>
     */
    public static final UdtPerson UDT_PERSON = new UdtPerson();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UdtPersonRecord> getRecordType() {
        return UdtPersonRecord.class;
    }

    /**
     * The attribute <code>jooq_sample.udt_person.id</code>.
     */
    public static final UDTField<UdtPersonRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT, UDT_PERSON, "");

    /**
     * The attribute <code>jooq_sample.udt_person.name</code>.
     */
    public static final UDTField<UdtPersonRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.CLOB, UDT_PERSON, "");

    /**
     * No further instances allowed
     */
    private UdtPerson() {
        super("udt_person", null, null, false);
    }

    @Override
    public Schema getSchema() {
        return JooqSample.JOOQ_SAMPLE != null ? JooqSample.JOOQ_SAMPLE : new SchemaImpl(DSL.name("jooq_sample"));
    }
}
