/*
 * This file is generated by jOOQ.
 */
package org.jooq.sample;


import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Result;
import org.jooq.sample.tables.AllPersons;
import org.jooq.sample.tables.records.AllPersonsRecord;


/**
 * Convenience access to all stored procedures and functions in jooq_sample
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>jooq_sample.all_persons</code>.
     */
    public static Result<AllPersonsRecord> allPersons(Configuration configuration) {
        return configuration.dsl().selectFrom(org.jooq.sample.tables.AllPersons.ALL_PERSONS.call()).fetch();
    }

    /**
     * Get <code>jooq_sample.all_persons</code> as a table.
     */
    public static AllPersons allPersons() {
        return org.jooq.sample.tables.AllPersons.ALL_PERSONS.call();
    }
}
