/*
 * This file is generated by jOOQ.
 */
package org.jooq.sample;


import javax.annotation.Generated;

import org.jooq.sample.udt.FullPersonRecord;
import org.jooq.sample.udt.UdtAddress;
import org.jooq.sample.udt.UdtPerson;
import org.jooq.sample.udt.UdtPhone;


/**
 * Convenience access to all UDTs in jooq_sample
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UDTs {

    /**
     * The type <code>jooq_sample.full_person_record</code>
     */
    public static FullPersonRecord FULL_PERSON_RECORD = org.jooq.sample.udt.FullPersonRecord.FULL_PERSON_RECORD;

    /**
     * The type <code>jooq_sample.udt_address</code>
     */
    public static UdtAddress UDT_ADDRESS = org.jooq.sample.udt.UdtAddress.UDT_ADDRESS;

    /**
     * The type <code>jooq_sample.udt_person</code>
     */
    public static UdtPerson UDT_PERSON = org.jooq.sample.udt.UdtPerson.UDT_PERSON;

    /**
     * The type <code>jooq_sample.udt_phone</code>
     */
    public static UdtPhone UDT_PHONE = org.jooq.sample.udt.UdtPhone.UDT_PHONE;
}
